NjProject/NjProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from NjProject import views
import account.views



urlpatterns = [
    path('admin/', admin.site.urls),
    #로그인 관련 url
    path('login/', account.views.login, name='login'),
    path('signup/', account.views.signup, name='signup'),
    path('logout/', account.views.logout, name='logout'),

    path('', views.HomeView.as_view(), name = 'home'),

    #todolist
    path('todolist/', include('todolist.urls')),

]

NjProject/todolist/urls.py
from django.urls import path
from . import views


app_name = 'todolist'

urlpatterns = [
    #todolist/
    path('', views.IndexView.as_view(), name = 'index'),

    #todolist/new
    path('new/', views.todolistnew, name = 'new'),

    #todolist/99
    path('<int:pk>/', views.todolistDetail.as_view(), name = 'detail'),

    #todolist/99/edit
    path('<int:pk>/edit', views.todolistedit.as_view(), name = 'edit'),

]

NjProject/account/models.py
from django.db import models

# Create your models here.

NjProject/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TodoList(models.Model):
    #TodoList 제목
    TodoList_text = models.CharField(max_length=200)
    #TodoList 내용
    TodoList_content = models.TextField()
    #TodoList 언제 해야 하는건지
    TodoList_when = models.DateTimeField('target time')
    #TodoList 했는지 안했는지 체크
    TodoList_bool = models.BooleanField(default=False)
    #todoList 위치
    TodoList_where = models.TextField(blank=True)

    #사용자 확인
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    #todoList 제목으로 출력
    def __str__(self):
        return self.TodoList_text

NjProject/todolist/forms.py
from django import forms
from todolist.models import TodoList

class TodolistForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ('TodoList_text','TodoList_content','TodoList_when','TodoList_bool','TodoList_where','user')

NjProject/NjProject/views.py
from pprint import pprint
from django.views.generic.base import TemplateView
from django.apps import apps

#--- TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['app_list'] = ['todolist']
        return context

NjProject/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
# Create your views here.

# 회원 가입
def signup(request):
    # signup 으로 POST 요청이 왔을 때, 새로운 유저를 만드는 절차를 밟는다.
    if request.method == 'POST':
        # password와 confirm에 입력된 값이 같다면
        if request.POST['password'] == request.POST['confirm']:
            # user 객체를 새로 생성
            user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
            # 로그인 한다
            auth.login(request, user)
            return redirect('/')
    # signup으로 GET 요청이 왔을 때, 회원가입 화면을 띄워준다.
    return render(request, 'signup.html')

# 로그인
def login(request):
    # login으로 POST 요청이 들어왔을 때, 로그인 절차를 밟는다.
    if request.method == 'POST':
        # login.html에서 넘어온 username과 password를 각 변수에 저장한다.
        username = request.POST['username']
        password = request.POST['password']

        # 해당 username과 password와 일치하는 user 객체를 가져온다.
        user = auth.authenticate(request, username=username, password=password)
        
        # 해당 user 객체가 존재한다면
        if user is not None:
            # 로그인 한다
            auth.login(request, user)
            return redirect('/')
        # 존재하지 않는다면
        else:
            # 딕셔너리에 에러메세지를 전달하고 다시 login.html 화면으로 돌아간다.
            return render(request, 'login.html', {'error' : 'username or password is incorrect.'})
    # login으로 GET 요청이 들어왔을때, 로그인 화면을 띄워준다.
    else:
        return render(request, 'login.html')

# 로그 아웃
def logout(request):
    # logout으로 POST 요청이 들어왔을 때, 로그아웃 절차를 밟는다.
    if request.method == 'POST':
        auth.logout(request)
        return redirect('/')

    # logout으로 GET 요청이 들어왔을 때, 로그인 화면을 띄워준다.
    return render(request, 'login.html')

NjProject/todolist/views.py
from django.views.generic import DetailView
from django.views import generic
from todolist.models import TodoList
from django.shortcuts import get_object_or_404, render
from .models import TodoList
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import TodolistForm
from django.contrib.auth import get_user_model

#from account.models import User

# Create your views here.

#def index(request):

class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_todolist_list'

    def get_queryset(self):
        return TodoList.objects.order_by('TodoList_when')[:]

class todolistDetail(DetailView):
    template_name = 'detail.html'
    model = TodoList

class todolistedit(DetailView):
    template_name = 'edit.html'
    model = TodoList


def todolistnew(request):
    if request.method == 'POST':
        form = TodolistForm(request.POST)
        if form.is_valid():
            temp = form.save(commit=False)
            #temp.user = user.username
            #temp.bool.. = true
            temp.save()
            return redirect('todolist:index')
    else:   
        form = TodolistForm()
    context = {'form': form }
    return render(request, 'new.html', context)

NjProject/account/templates/login.html
<form method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    <p>username</p>
    <input type="text" name="username">
    <br>
    <p>password</p>
    <input type="password" name="password">
    <br>
    <input type="submit" value="로그인">
</form>

NjProject/account/templates/signup.html
<form method="POST" action="{% url 'signup' %}">
    {% csrf_token %}
    <p>username</p>
    <input type="text" name="username">
    <br>
    <p>password</p>
    <input type="password" name="password">
    <br>
    <p>password confirm</p>
    <input type="password" name="confirm" />
    <br>
    <input type="submit" value="회원가입">
</form>

NjProject/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}" />
    <title>{% block title %}Namju's To Do List{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        
        &nbsp;&nbsp;&nbsp;&nbsp;<a href="/">홈 화면으로</a>
        <a href="/admin/">Admin</a>
        <ul>
            {% if user.is_authenticated %}
            <p>{{ user.username }}</p>
            <a href="javascript:{document.getElementById('logout').submit()}">로그아웃</a>
            <form id="logout" method="POST" action="{% url 'logout' %}">
                {% csrf_token %} <input type="hidden" />
            </form>
            
            {% else %}
            <a href="{% url 'signup' %}">회원가입</a>
            <a href="{% url 'login' %}">로그인</a>
            {% endif %}
        </ul>
        {% endblock %}
        <br>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>



    {% comment %}
        <p>oanhglkansg</p>
    {% endcomment %}

</body>

</html>

NjProject/templates/home.html
{% extends "base.html" %}

{% block content %}
    <h2>Applications list</h2>
    <ul>
        {% for appname in app_list %}
{% with appname|add:":"|add:"index" as urlvar %}
            <li><a href="{% url urlvar %}">{{ appname }}</a></li>
{% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}

NjProject/templates/todolist/new.html
{% extends "home.html" %}
{% block content %}
<form method="POST" >
    {% csrf_token %}
    <h3>제목</h3>
    <input type="text" name="TodoList_text" />
    <h3>내용</h3>
    <input type="text" name="TodoList_content" style=" width: 500px; height: 300px;" />
    <h3>시간</h3>
    <input type="datetime-local" id="start1" name="trip-TodoList_when">


    <h3>장소</h3>
    <input type="text" name="TodoList_text"/>

    <br>
    <input type="submit" value="저장하기">
</form>
{% endblock content %}

NjProject/todolist/templates/detail.html
{% extends "base.html" %}


{% block content %}

<h3>제목</h3>
<h1>{{ object.TodoList_text }}</h1>
<h3>내용</h3>
<p>{{ object.TodoList_content }}</p>
<h3>시간</h3>
<p>{{ object.TodoList_when }}</p>
<h3>완료여부</h3>
{% if object.TodoList_bool %}
<p>완료</p>
{% else %}
<p>미완료</p>
{% endif %}

<h3>장소</h3>
<p>{{ object.TodoList_where }}</p>

<br>
<a href="{% url 'todolist:edit' todolist.id %}">수정하기</a>

{% endblock content %}

NjProject/todolist/templates/edit.html
{% extends "home.html" %}


{% block content %}

<h3>제목</h3>
<form method="update" >
    {% csrf_token %}
    <input type="text" name="TodoList_text" value="{{ object.TodoList_text }}" />
    <h3>내용</h3>
    <input type="text" name="TodoList_content" value="{{ object.TodoList_content }}"
        style="width: 500px ;height: 300px;" />
    <h3>시간</h3>
    <input type="datetime-local" id="start" name="trip-TodoList_when" value="{{todolist.TodoList_when|date:'Y-m-d'}}T{{todolist.TodoList_when|time:'H:i:s'}}">
    <h3>완료여부</h3>
    {% if object.TodoList_bool %}
    <input type="checkbox" name="TodoList_bool" value="HTML" checked>
    {% else %}
    <input type="checkbox" name="TodoList_bool" value="HTML">

    {% endif %}

    <h3>장소</h3>
    <input type="text" name="TodoList_text" value="{{ object.TodoList_where }}" />


    <br>
    <input type="submit" value="수정하기">
</form>


{% endblock content %}

NjProject/todolist/templates/index.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'todolist:new' %}">새로 만들기</a>

<h2>todolist List</h2>

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>우선순위</th>
            <th>제목</th>
            <th>목표시간</th>
            <th>작성자</th>
        </tr>
        </thead>    
        <tbody>
            {% if latest_todolist_list %}
            {% for TodoList in latest_todolist_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'todolist:detail' TodoList.id %}">{{ TodoList.TodoList_text }}</a>
            </td>
            <td>{{ TodoList.TodoList_when }}</td>
            <td>{{ TodoList.user }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">No Todolist</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div

{% endblock %}

NjProject/todolist/templates/new.html
{% extends "home.html" %}
{% block content %}
<form method="POST" >
    {% csrf_token %}
    <h3>제목</h3>
    <input type="text" name="TodoList_text" />
    <h3>내용</h3>
    <input type="text" name="TodoList_content" style=" width: 500px; height: 300px;" />
    <h3>시간</h3>
    <input type="datetime-local" id="start1" name="trip-TodoList_when">


    <h3>장소</h3>
    <input type="text" name="TodoList_text"/>

    <input type="submit" value="저장하기">
</form>
{% endblock content %}